/* Backup seguro do Pão da Dilma no Google Drive.
   Requer apenas o CLIENT_ID do OAuth do Google Cloud em GOOGLE_CLIENT_ID. */
const DRIVE_CONFIG={CLIENT_ID:"855482975063-94b5bg9pdffvhg85qsuga7m2a5l2h0dk.apps.googleusercontent.com",SCOPE:"https://www.googleapis.com/auth/drive.file",FOLDER:"Pao da Dilma - Backup",FILE:"pao-da-dilma-dados.json"};
let driveToken=null, driveBusy=false;
function driveStatus(t,ok=false){const e=document.querySelector('#driveStatus');if(e){e.textContent=t;e.className='driveStatus '+(ok?'ok':'')}}
function driveConfigured(){return DRIVE_CONFIG.CLIENT_ID && !DRIVE_CONFIG.CLIENT_ID.includes('COLOQUE_SEU')}
function driveAuth(){
 if(!driveConfigured()){driveStatus('Configure o ID do Google no drive.js.');toast('Falta configurar o Google Drive.');return}
 if(!window.google?.accounts?.oauth2){driveStatus('Carregando autorização do Google...');setTimeout(driveAuth,700);return}
 const client=google.accounts.oauth2.initTokenClient({client_id:DRIVE_CONFIG.CLIENT_ID,scope:DRIVE_CONFIG.SCOPE,callback:async r=>{if(r.error){driveStatus('Autorização cancelada.');return} driveToken=r.access_token; localStorage.setItem('pao_drive_connected','1'); driveStatus('Google Drive conectado. O backup só será feito quando você solicitar.'); toast('Google Drive conectado!');}});
 client.requestAccessToken({prompt:''});
}
async function driveFetch(url,opts={}){if(!driveToken)throw new Error('Drive não conectado');const headers=new Headers(opts.headers||{});headers.set('Authorization','Bearer '+driveToken);opts.headers=headers;const r=await fetch(url,opts);if(r.status===401){driveToken=null;throw new Error('Autorização expirada. Conecte novamente.')}if(!r.ok)throw new Error(await r.text());return r}
async function driveFind(name,mime){const q=`name='${name.replace(/'/g,"\\'")}' and trashed=false`;const r=await driveFetch('https://www.googleapis.com/drive/v3/files?q='+encodeURIComponent(q)+'&spaces=drive&fields=files(id,name,mimeType,modifiedTime)');return (await r.json()).files||[]}
async function driveFolder(){let f=(await driveFind(DRIVE_CONFIG.FOLDER,'application/vnd.google-apps.folder')).find(x=>x.mimeType==='application/vnd.google-apps.folder');if(f)return f.id;const meta={name:DRIVE_CONFIG.FOLDER,mimeType:'application/vnd.google-apps.folder'};const r=await driveFetch('https://www.googleapis.com/drive/v3/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(meta)});return (await r.json()).id}
function backupPayload(){return JSON.stringify({app:'Pão da Dilma',version:1,updatedAt:new Date().toISOString(),data:state},null,2)}
async function uploadMultipart(metadata,content,fileId=null){const boundary='paoDilmaBoundary'+Date.now();const body='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(metadata)+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+content+'\r\n--'+boundary+'--';const url=fileId?`https://www.googleapis.com/upload/drive/v3/files/${fileId}?uploadType=multipart`:'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart';const r=await driveFetch(url,{method:fileId?'PATCH':'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});return r.json()}
async function backupNow(){if(driveBusy)return;if(!driveToken){driveStatus('Backup local ativo; conecte o Google Drive.');return}driveBusy=true;driveStatus('Salvando backup no Google Drive...');try{const folderId=await driveFolder();let fileId=localStorage.getItem('pao_drive_file_id');if(!fileId){const files=await driveFind(DRIVE_CONFIG.FILE);if(files[0])fileId=files[0].id}const meta={name:DRIVE_CONFIG.FILE,mimeType:'application/json',parents:fileId?undefined:[folderId]};const out=await uploadMultipart(meta,backupPayload(),fileId);localStorage.setItem('pao_drive_file_id',out.id);localStorage.setItem('pao_drive_last_backup',new Date().toISOString());driveStatus('✓ Backup atualizado: '+new Date().toLocaleString('pt-BR'),true)}catch(e){console.error(e);driveStatus('Backup não concluído: '+e.message);toast('Não foi possível atualizar o backup.')}finally{driveBusy=false}}
async function restoreNow(){if(!driveToken){toast('Conecte o Google Drive primeiro.');return}if(!confirm('Restaurar os dados do Google Drive? Os dados atuais deste aparelho serão substituídos pelo backup.'))return;driveStatus('Baixando backup...');try{let fileId=localStorage.getItem('pao_drive_file_id');if(!fileId){const files=await driveFind(DRIVE_CONFIG.FILE);if(!files[0])throw new Error('Backup não encontrado');fileId=files[0].id}const r=await driveFetch(`https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`);const obj=await r.json();if(!obj.data?.clients||!obj.data?.sales)throw new Error('Arquivo de backup inválido');localStorage.setItem(KEY,JSON.stringify(obj.data));localStorage.setItem('pao_drive_file_id',fileId);driveStatus('✓ Dados restaurados do Google Drive.',true);toast('Dados restaurados!');setTimeout(()=>location.reload(),500)}catch(e){driveStatus('Falha ao restaurar: '+e.message);toast('Não foi possível restaurar o backup.')}}
function driveDisconnect(){driveToken=null;localStorage.removeItem('pao_drive_connected');driveStatus('Google Drive desconectado.');toast('Drive desconectado neste navegador.')}
